server:
  port: 7001
spring:
  profiles:
    active: dev
flyway:
  baseline-version: 1.0
---
spring:
  profiles: dev
  datasource:
#    url: jdbc:h2:file:~/.h2/test
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
flyway:
  locations: classpath:db/migration/h2