spring:
  application:
    name: promotion
server:
  port: 7001
eureka:
  client:
    service-url:
      default-zone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
flyway:
  locations: classpath:db/migration/h2
  baseline-version: 1.0